# Generated by Django 5.2.7 on 2025-10-04 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyrics', models.TextField(help_text='The raw lyrics provided by the user.')),
                ('genre', models.CharField(choices=[('afrobeats', 'Afrobeats'), ('highlife', 'Highlife'), ('gengetone', 'Gengetone'), ('amapiano', 'Amapiano'), ('pop', 'Global Pop'), ('hiphop', 'Global Hip-Hop')], default='afrobeats', max_length=50)),
                ('mood', models.CharField(choices=[('celebratory', 'Celebration/Joy'), ('resilience', 'Resilience/Hope'), ('love', 'Love/Affections'), ('harvest', 'Harvest/Abundance'), ('protest', 'Protest/Activism'), ('reflection', 'Reflection/Contemplation')], default='celebratory', max_length=50)),
                ('voice_type', models.CharField(blank=True, help_text='Requested voice type, if supported by API.', max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Generation'), ('AUDIO_READY', 'Audio Generated'), ('VIDEO_READY', 'Video Generated'), ('FAILED', 'Generation Failed')], default='PENDING', max_length=20)),
                ('audio_url', models.URLField(blank=True, help_text='S3/Firebase URL for the generated audio file.', max_length=500, null=True)),
                ('video_url', models.URLField(blank=True, help_text='URL for the generated music video.', max_length=500, null=True)),
                ('remix_count', models.PositiveIntegerField(default=0, help_text='Number of times this song has been remixed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remix_of', models.ForeignKey(blank=True, help_text='Link to the original SongRequest if this is a remix.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remixes', to='generator.songrequest')),
                ('user', models.ForeignKey(help_text='The user who initiated the request.', on_delete=django.db.models.deletion.CASCADE, related_name='song_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
