# Generated by Django 5.2.7 on 2025-10-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the generated audio in seconds.', null=True),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this song can be viewed or remixed by others.'),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Luganda', 'Luganda'), ('Swahili', 'Swahili'), ('Yoruba', 'Yoruba'), ('French', 'French'), ('Arabic', 'Arabic')], default='English', help_text='Language of the lyrics.', max_length=50),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title for the song.', max_length=200, null=True),
        ),
    ]
